apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
spec:
  replicas: 2  # Number of replicas of your application
  selector:
    matchLabels:
      app: new_app
  template:
    metadata:
      labels:
        app: new_app
    spec:
      containers:
        - name: new-app
          image: dockerraziza/new_app  # Docker image name
          ports:
            - containerPort: 80  # Exposed application port
