apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new_app
  template:
    metadata:
      labels:
        app: new_app
    spec:
      containers:
        - name: new_app
          image: dockerraziza/new_app
          ports:
          - containerPort: 80
